; generated by PrusaSlicer 2.9.2 on 2025-12-17 at 01:12:05 UTC


;
; thumbnail begin 160x120 6624
; iVBORw0KGgoAAAANSUhEUgAAAKAAAAB4CAYAAAB1ovlvAAATLklEQVR4Ae2d+ZMU1R3A5+9JqjSmKl
; X+lEqlUik1+SEkRiMLgiCwgOi63MulohyCq7vKwrLL5QEuwiIIAsp9KKKCi6BYoiVQRVGKinKfL/k8
; 8sbednqmj/dev+4Zq75yzcxO9/v0937fV+jbt69QMnz4cLFq1SrR1dUlJk6cKPr37y8mTJgg3n33Xb
; F48WLxyCOPCO/rTUhdXV1Vy6hRo8Thw4fF/PnzxeOPPy4efPBBuQaffPKJmD17tqivr8/U9VSSglr4
; WbNmiTVr1oj29nYxZMiQXlAMHDhQrFixQnR3d4snn3xS9OvXrwbe/6Vt0G3aPquzs1Ps3btXTJs2TQ
; wbNqzXvwHi+vXrpYIATJSDjeszDiBwLV++XF7YU089JS8sCJAZM2aIjRs3ipdeekk8/PDDVa3tAK9n
; eEFKUggHDRokPvroI/Hqq6+KsWPHigEDBgS+Fi344YcfiqlTp8o1SOPatQL45ptvipdffjm0eeXJXL
; dunYQW08CHVAt0ShR4XokLIUAdOnRIWqCRI0dK61LpPUOHDhXvvfeedIsw2WHe4yyAc+fOlSY2CkRc
; 8Isvvijeeustwft5YqsBvCD44oK4adMm+TA3NTVJLRjle7AGHR0dYvv27WLcuHHioYceSu2eJAKQ/8
; U1oaNHj5YmecmSJeKxxx6ravCiQIiZPXLkiHjhhRfkfUviz+EPfvzxx6K5uVkGkWndn9gAxoVPCc7x
; 0qVLZYDy9NNP58Y5jgtfJRBfe+01qbXw4Qj2dHw/1mD16tVi7dq1Uinw57TvmTUAlZZ74oknxObNm8
; WCBQt+FcFlVbyBRlIIuSf4eliLMWPGlA004gpB5MGDB+Wv+Iku3UvjACJEZWhC8oiTJk3KxA0IkqTg
; eWXtlLvFwY5h0kJgJk0GDfiSaFgi6qTm3XkAS30gNxd/ZMOGDdLHiepcuyA64fNK+5A7rHx/1oBU2Z
; 49e2RBweU1KOgCzy+kB4CQFA9+ias3wAZ4UQIUnUJqjfzivHnzQqd4nAYw6oej/kkV4ByT53LZObYB
; Xy8QB98mgdAl5daAwIdshSnf0ziASX8I/uA777wjYeRJdOkG2AbPJITl4GQNDhw4IKtZBESuaMOCaf
; iUkCglOKHkR63ThRuQJnxeCG2BiPZDE7IOrtSTC6bB8wo3AVPsrSencdE60itZ1YbIc889Jz744AMx
; ZcoUuQZpKoOCDfD8QiqCMh6+yfjx463eANfASwtC2rqAELdI1ZPD+JRGAbT1QxHUf1tbmwRxzpw5xp
; xj7011Gb40QGQNaGjYunVrsZ5c6nUmOSjYBs8v1EUpynMjSJzqhi5L4KUBIUJ0TD2ZxhKVKA8S3etf
; MAVWFEH7vfLKK7KKMn369FjOcdANyxJ0pSC0BSIpMlrzaEpubGyUf7YBohMAKoCAD21IO3qYenK5G8
; TCZQk2V7QhaRrSNXS+0ywR5j25AFAJRXQS16+//rrMXfkvMMwNMQ3EqvvTgdAWiETGu3btklWsRx99
; VFokUyA6ByDCBVNHppT3/PPPy1pm2JtnGoSGOwti5l/SgdC2NsQSASKd71HWIPMAKmloaBBvv/22fB
; LxS9IEb2mfW/ApAKsFQjQg9eTW1tZiPVkniE4C6L0InGEiZBzkmTNnlnSOTS+4As8PYLWAyD2neoJF
; UvVkXSA6BWC5i6CDmHrywoULxYgRI+Tf2Qg0/PCVAhBJA0CbEKo1oOH1mWeeKdaTk4KYOoBRLmDw4M
; HijTfekJIGeErQeK5oQQWhLRDZwIYiYJ84LlLYACUIwtQAjHsD0tJ6StRr/BCmCWAa2pAg8f3335eZ
; ChRD1PfjW9ITYB3AJBdtegG9gUYQeF4BOgWiCwDahhBXiE3y7AOi+TXs+2iGYNTI1atX7QLoMnxhtF
; 6QKBDThi8NEDHBy5Ytk/ODqCdjooNeS34R9+n06dPi2rVr4saNG3YAdBm8clqPfwv7OWkGImlDiNDV
; RAWFSQ+l6snsmmSaw5UrV8T169fFzZs3pQk3CmDSizK9QEm0nl9c04BeCG02vNLdxB5lVU9G2Ir69d
; dfF7Xezz//LNM6tIEZATDphbgSaOQBQC+INiBEaDqm15B2u507d4rz588Xtd6nn34qq1uYaljRDmDS
; L296IXSD5wWwBuEvQr727NmzMtBA62F6SWRjqlW3E6/TBqCOL216AaJGuXkD0AaIJKipWp05c0aaXL
; TehQsX5EZ5VUDwSmIAswCeH0IviDo/Ow6Ak/+YXneNbvho5dq/f7/Uephc/qOZgZwh9WR+9UOYCMCs
; wecHUfdnRgFJPQAAqPKIWQURfw4Nd+LEiWKg8f333/fSegQo7IgkSGFQgaonxwJQ1xPT+I/bMmO2wk
; jYVIzX9CsA06io8BAOvScZgIz+2LFjh7h48WIx0CAd493n4309ja7Uk2k+pvczMoC64FMApvn065ZK
; 11DK9/QDaAtC9fOTAEgF5OjRo8VA49KlS9L/Q8OVqxHTW8hGKHZFFtKCzwugS/VUUwAGBT9+AG18T+
; /PjwMgZTci2p9++qkYaHz55Zcy7RKlcZUpu4U0wAsCMOsQltLkYSotqp5sE7y4AGJaMbEq0EDzbdmy
; RW5yr7SRqZQU0oIvCMAsg+gH0FTOURd8UQCk42XlypXi1KlTxUCDmi7TceP0BoYC0CR8lQDMMoTlFt
; xE9B0HvCgA0ojKrMHLly8XAw0qHXSoR+2ODg2gafjCAJjFAAWfznWtFxZAAolFixaJY8eOFQMNymp0
; tKjpq0kZKKQBXhQAs6YNgwC0+R3K+Z1hAaSZgM7nc+fOFQONzz77TLS0tJRtuUoEoE34ogKYFQj9i2
; /754cFrxyAVCxoGlCBBr/SvUzOL06gEQpA2/DFATALIJoq85mAzw8giWFGc3z33XfFQOPkyZNyglbY
; KQmxAEwDviQAugyhqjXb/JlxwPMDyAT/ffv29arjEnhQsUgaaJQFMC34kgKYNd/QRfiQ+r//Tg6GOn
; 78eFHr/fjjj3LXGxvRdQQauQawWiGMEmiUk/mTBsh2KZVe6enpkZuGdAYazgI4Z8RdWgDMYromiegA
; T8mG9ilS65Hj4+BE5jXqDjScAxC1zmk+HRPv1wZgtWhDnfAhGzumia+++ko2FsTZ35s5AKkZkk9iX8
; CkvndqBzCvEOoGr2iCJw+UpxaYDDScAZAMOvtHgZCwXpcPmHcQTcGHjOrzB+OBRuoAEk2R2CSf5O2G
; NQ1g1iE0CZ4SlYZJC0LjAOJbULjmCFH/hmUbAGY1QLEBHzLsb7dL+JTkBkBG/rPznVG7bMUrdQSALQ
; CzpA11pVfiAmgbQiMAklUn0KB5kd3vQRdlG0DXIbQJXjkAbUKoHcD169fLsbqM7VLHQAVJGgC6CmIa
; 8JUD0BaE2gDk8LsjR47Is2n5fZhkZpoAugKhDoha7q5yAGnL3r17t5yAFKU9O20AFYRpgagDvnUPmA
; PQBoSJACSXxx5PitmUcKLWD10AMA1tqCvQAD7ElAm2AWGB9EicN3KuGFMu2RcQt2vCJQBtaUOd4NkC
; 0CSEBWa5MeEySimGagYbkJuamiLtA3UdQNPa0AR8ScyvEwCyuYRzOIhcMaPlXkxLNukVWrZ5X9KuCV
; cB1A2hDvAQYNOp/aIAaApC6QPiu5Gz44w2TjIvBRYJ5W3btskterRu6/jhjX1udxZAXSDqgs+E9nMG
; QCWcCcZEI0BUU40on1HHZXtenFNygoQLygKAcSE0UdHQrf2iAmgCwl9FwUS21G/p16NBkblu7AuodJ
; BxVPiyBKCCMCyIusEzZX6dBBAhsDh8+LD44osvxObNm0tOtkwKX9YADKMNTdZxTZhfJwFkftvnn38u
; 0yyU0whQ2KA8efJkrfBlFcAgCHXAcN9vb8ng31cGUBfYUQHUDWEvAEmtsAEZ2FQdF5+Psx/wCxk8Hd
; cHLHUhWQXQD6IuGABPQWjD/DoDIOd2YXI5oDiojksAwrm9jFjl9TUAb4kuELwQKjFtfp0AsLOzU+zd
; u1fWcevr68u+mE0r5ADpeGHrXtgvE3QhNQArg1gKQJ0/J3UAGZNa6YwvP0zs6SAvSBWl0siGchdSA7
; AyhCbNb1wAdUJYYNxqnA8kLUO6Bp8R7Rn0GTUAk8mgOwpi+p/NmF8nAEzyZgISTs/u7u6WLVn+AKXS
; RdQADA/hvb+5BaLuz840gEoIXDiQjnoyu95qAJoBEOH3NQBLCJuOCEyonjD9nEi6BqAZCGsABghfjI
; 6Z5cuXy7whfmINQP0Q6tSCuQJQCW357A3BJOMj1gDUJ7pNcS4B5AtiginrcT4YqR5MdA3AytJ81y0J
; +vfWe/RCmDsA/V+UqgnJ7k2bNknzXAOwMoCr7y8Nobf2DIg1AEMAiJDkfvbZZ6VfSO6QdE0NwNICfE
; qUNgwa+asDQqeaEUwBqISKCzvoqCeTAK8BWB5ApNK8aSBM0gaWKwDDfHlKd62trfKwu9n1f80UbKYB
; VObXK/x9OQiT9iBO6PenUCmz3ACoAhT2liwY/+9MwWYaQD98Xj/QVOc1pVT2AbHPp2oAVMJ+4vb2dr
; Fkar9MQWcLQO+/ebWgrs5rtQZ0N5G7ZU9QVQGIEJDMmDFDdDT9J1Pg6QYwyPx6RZfWK2WR6AXFN6cT
; vlTKzAR8WgGMA59XqCGzQX7xlLqqBLCc+dUp5daAOY7sAaKu39DQUF0AIjS8Mrx80eS+VQ+gbvDCRr
; ukzCgc0OHEnEd/gJJrAJWwGWr+uHszYZZ1wIFPt32gOQDjrAHwoQ0xzXTKm4DPWQARLrqtrc35AEUH
; ICq4UBDqNL9J14DuJrrfUQpVowGVEKCwKX6hgQNtXAGwVI4vbfC8gglWeVvcoyTDqDIHoBI1QMlFba
; hL+7kIn1doOiZnyM5IAkZd2jATACKkBhigtGjSA7kEUAd4cRsLKolaYywSETL7x5kLqWNOUGYAVEKy
; dN6YfzoDog7zqwM+k/fcv84c7cW0DAYVJB3bkjkAEcpGtP27kDNMCqCrWq8UfF5hcga9nhy/BpDlXl
; tKVDk29UpIXOEC2A7aPuG+zALostarBKBabyon+IYohErHcnjhJbAB3swCqIS2Ls6gWzqtf1UBaOPe
; hl131oAomdmStNwFvZe/ZwovfiTwMe4l8wAiZO9nzZqVSuI6j+BFgc9rUmksIW9I87E/QOHPrNGKFS
; tkfhc3qq6uLh8AKuGJmje6j1hmURvW4OstbLuggsJEXbZj8Hmq64nyHn4fCgP4eH2uAETwL2j77547
; MjcAmg40dAKIkDKjvYsghUiZJhPyh4CowFNitSXflhbcsmWLuHDhgti5dKrYvWxapgG0ff90ccDWXI
; ZXHT16VO4FamxsLPn5uQKQSIw5h1evXhU3btyQvzLttWvm0EwCaPv+6Vp/zDBar6urSw47ZUckv1e7
; Io0CmAaEFM3Jzp85c0Zcu3ZN3Lx5Uxw/flyqf/6NrH2HoXpyHsDTBZ8azwJspFnY/4PJJUCh7Z/O6+
; bm5l5nR2ceQLqp9+/fL7Xd9evXBf/t2rVLntCuIjFepwYoLdGcvK7B98v9JfDA7KLpuPd+f48aMtqQ
; SWq83hiANiDkKSLvdOLECan1MLk//PCDbKZUZ9f5hU4OnlCdZTxd4NkONHTBp0b0EXQwgACL4wfP/3
; rM85o1a+T7MgkgT9iOHTvExYsXpdbD5HJqJ1l5Nem10vvbxv5LdGoAMataTwd8wEbDKukV2uZQCuXg
; 8wpVLNI1xgA0BSEpFiIrFWhcunRJ+n9Ev1H2t6oBSklNcjXCx30muCC1guaLM7QewUfMDICq3HP27N
; lioHHs2DGZVce0xvlMNUApST05a+AlhY99Oy0tLWLlypUyoCDvGlbrlRKjAOqCkD7AAwcOFAMNNN/W
; rVtlVt0baMQVNUApTsNrtcDHe7EyNAaTYKamywOcBD4rACaBg6eNJ+3UqVPFQOP06dPSiVUbZXQJvi
; MH8kStJ1eD1vPWcXGBcF+SgmcVwDgQot327NkjLl++XAw0SLdwI8IEGnGFbg7Z8Bpya2jetR6uD/lU
; olb6/rx13EwBGAUY8kn4d0rrnT9/Xqp9NkurU5xMLhh+DX5OGAhdTa8khU/1WzLNTNVxTTBhFcBK4F
; AvpNX73LlzxUCDE9rJqqvsua2FCztAKY8ml+iUygUPPW4JrpBOrZcqgEEQcQTYoUOHioEGAJI1b2pq
; sqL1goQ9D+UGKOXN5LLnhkoFvndQA0HmAfTCRGMiicxvv/22aHJPnjwpo1KeRHUD0lzQ4gClEvXkvG
; g9fDsS+WxCp6lDNYya5iA1ABGy5/v27StqPUwugQdjIXSkV3QLGgHt4N0MlfWkMu9n3zUPPHVcJiCU
; quPmCkAuEMf2m2++KWo9EsyE+d6z69Ja0HJC0psErApQ0g40kq4DSoD6Ofk9znWxBV5qADICbNu2bb
; JhVGm9np4euajeEzvTWtCwgm86/3/1ZMqAunOSpsFDyOVRRULr0RTAg2UbPusAcsFEtaqOS46PTSzk
; 3tIMNOKKWkQO5MFtsPEzk64B9xkzSzIffw/zaxs6r/wXS7L+NHx0b4gAAAAASUVORK5CYII=
; thumbnail end
;
; 

; external perimeters extrusion width = 0.60mm
; perimeters extrusion width = 0.50mm
; infill extrusion width = 0.50mm
; solid infill extrusion width = 0.50mm
; top infill extrusion width = 0.45mm
; first layer extrusion width = 0.42mm

M73 P0 R6
M73 Q0 S6
M201 X1000 Y1000 Z200 E5000 ; sets maximum accelerations, mm/sec^2
M203 X200 Y200 Z12 E120 ; sets maximum feedrates, mm / sec
M204 S1250 T1250 ; sets acceleration (S) and retract acceleration (R), mm/sec^2
M205 X8.00 Y8.00 Z0.40 E4.50 ; sets the jerk limits, mm/sec
M205 S0 T0 ; sets the minimum extruding and travel feed rate, mm/sec

; printing object xyz-10mm-calibration-cube(3).stl id:0 copy 0
; stop printing object xyz-10mm-calibration-cube(3).stl id:0 copy 0

;TYPE:Custom
M862.3 P "MK3S" ; printer model check
M862.1 P0.4 ; nozzle diameter check
M115 U3.14.1 ; tell printer latest fw version
G90 ; use absolute coordinates
M83 ; extruder relative mode

G28 W ; home all without mesh bed level
G80 X120 Y100 W10 H10 ; mesh bed levelling


; stop printing object xyz-10mm-calibration-cube(3).stl id:0 copy 0
;WIPE_START
G1 F8640;_WIPE
G1 X121.776 Y100.979 E-.26026
;WIPE_END
G1 E-.73974 F2100
M107
;TYPE:Custom
; Filament-specific end gcode
G1 Z11.1 F720 ; Move print head up
G1 X0 Y200 F3600 ; park
G1 Z59.1 F720 ; Move print head further up
G4 ; wait
M221 S100 ; reset flow
M900 K0 ; reset LA

M104 S0 ; turn off temperature
M140 S0 ; turn off heatbed
M107 ; turn off fan
M84 ; disable motors
; max_layer_z = 10.1
M73 P100 R0
M73 Q100 S0
; objects_info = {"objects":[{"name":"xyz-10mm-calibration-cube(3).stl id:0 copy 0","polygon":[[130.000,110.000],[120.000,110.000],[120.000,100.000],[130.000,100.000]]}]}
; filament used [mm] = 295.74
; filament used [cm3] = 0.71
; filament used [g] = 0.90
; filament cost = 0.03
; total filament used [g] = 0.90
; total filament cost = 0.03
; total filament used for wipe tower [g] = 0.00
; estimated printing time (normal mode) = 6m 28s
; estimated printing time (silent mode) = 6m 29s
; estimated first layer printing time (normal mode) = 22s
; estimated first layer printing time (silent mode) = 22s

; prusaslicer_config = begin
; arc_fitting = disabled
; autoemit_temperature_commands = 1
; automatic_extrusion_widths = 0
; automatic_infill_combination = 0
; automatic_infill_combination_max_layer_height = 100%
; avoid_crossing_curled_overhangs = 0
; avoid_crossing_perimeters = 0
; avoid_crossing_perimeters_max_detour = 0
; bed_custom_model =
; bed_custom_texture =
; bed_shape = 0x0,250x0,250x210,0x210
; bed_temperature = 90
; bed_temperature_extruder = 0
; before_layer_gcode = ;BEFORE_LAYER_CHANGE\nG92 E0.0\n;[layer_z]\n\n
; between_objects_gcode =
; binary_gcode = 0
; bottom_fill_pattern = monotonic
; bottom_solid_layers = 3
; bottom_solid_min_thickness = 0.5
; bridge_acceleration = 1000
; bridge_angle = 0
; bridge_fan_speed = 50
; bridge_flow_ratio = 0.95
; bridge_speed = 25
; brim_separation = 0.1
; brim_type = outer_only
; brim_width = 0
; chamber_minimal_temperature = 0
; chamber_temperature = 0
; color_change_gcode = M600\nG1 E0.3 F1500 ; prime after color change
; colorprint_heights =
; compatible_printers_condition_cummulative = "printer_notes=~/.*PRINTER_VENDOR_PRUSA3D.*/ and printer_notes=~/.*PRINTER_MODEL_MK3.*/ and nozzle_diameter[0]==0.4 and printer_model!=\"MK3.5MMU3\"";"nozzle_diameter[0]!=0.8 and printer_model!=\"MK2SMM\" and printer_notes!~/.*MINI.*/ and printer_notes!~/.*PG.*/ and ! (printer_notes=~/.*PRINTER_VENDOR_PRUSA3D.*/ and printer_notes=~/.*PRINTER_MODEL_MK(2.5|3).*/ and single_extruder_multi_material) and printer_model!=\"MK3.5\""
; complete_objects = 0
; cooling = 1
; cooling_tube_length = 5
; cooling_tube_retraction = 91.5
; default_acceleration = 1000
; default_filament_profile = "Prusament PLA"
; default_print_profile = 0.15mm QUALITY @MK3
; deretract_speed = 0
; disable_fan_first_layers = 3
; dont_support_bridges = 0
; draft_shield = disabled
; duplicate_distance = 6
; elefant_foot_compensation = 0.2
; enable_dynamic_fan_speeds = 0
; enable_dynamic_overhang_speeds = 1
; end_filament_gcode = "; Filament-specific end gcode"
; end_gcode = {if layer_z < max_print_height}G1 Z{z_offset+min(max_layer_z+1, max_print_height)} F720 ; Move print head up{endif}\nG1 X0 Y200 F3600 ; park\n{if layer_z < max_print_height}G1 Z{z_offset+min(max_layer_z+49, max_print_height)} F720 ; Move print head further up{endif}\nG4 ; wait\nM221 S100 ; reset flow\nM900 K0 ; reset LA\n{if print_settings_id=~/.*(DETAIL @MK3|QUALITY @MK3|@0.25 nozzle MK3).*/}M907 E538 ; reset extruder motor current{endif}\nM104 S0 ; turn off temperature\nM140 S0 ; turn off heatbed\nM107 ; turn off fan\nM84 ; disable motors\n; max_layer_z = [max_layer_z]
; ensure_vertical_shell_thickness = enabled
; external_perimeter_acceleration = 0
; external_perimeter_extrusion_width = 0.6
; external_perimeter_speed = 35
; external_perimeters_first = 0
; extra_loading_move = -2
; extra_perimeters = 0
; extra_perimeters_on_overhangs = 0
; extruder_clearance_height = 20
; extruder_clearance_radius = 45
; extruder_colour = ""
; extruder_offset = 0x0
; extrusion_axis = E
; extrusion_multiplier = 1
; extrusion_width = 0.5
; fan_always_on = 1
; fan_below_layer_time = 20
; filament_abrasive = 0
; filament_colour = #FF8000
; filament_cooling_final_speed = 3.4
; filament_cooling_initial_speed = 2.2
; filament_cooling_moves = 4
; filament_cost = 27.82
; filament_density = 1.27
; filament_deretract_speed = nil
; filament_diameter = 1.75
; filament_infill_max_crossing_speed = 0
; filament_infill_max_speed = 0
; filament_load_time = 0
; filament_loading_speed = 28
; filament_loading_speed_start = 3
; filament_max_volumetric_speed = 8
; filament_minimal_purge_on_wipe_tower = 15
; filament_multitool_ramming = 0
; filament_multitool_ramming_flow = 10
; filament_multitool_ramming_volume = 10
; filament_notes = ""
; filament_purge_multiplier = 100%
; filament_ramming_parameters = "120 100 6.6 6.8 7.2 7.6 7.9 8.2 8.7 9.4 9.9 10.0| 0.05 6.6 0.45 6.8 0.95 7.8 1.45 8.3 1.95 9.7 2.45 10 2.95 7.6 3.45 7.6 3.95 7.6 4.45 7.6 4.95 7.6"
; filament_retract_before_travel = nil
; filament_retract_before_wipe = nil
; filament_retract_layer_change = nil
; filament_retract_length = 1
; filament_retract_length_toolchange = nil
; filament_retract_lift = 0.2
; filament_retract_lift_above = nil
; filament_retract_lift_below = nil
; filament_retract_restart_extra = nil
; filament_retract_restart_extra_toolchange = nil
; filament_retract_speed = nil
; filament_seam_gap_distance = nil
; filament_settings_id = "Generic PETG"
; filament_shrinkage_compensation_xy = 0%
; filament_shrinkage_compensation_z = 0%
; filament_soluble = 0
; filament_spool_weight = 0
; filament_stamping_distance = 0
; filament_stamping_loading_speed = 20
; filament_toolchange_delay = 0
; filament_travel_lift_before_obstacle = nil
; filament_travel_max_lift = nil
; filament_travel_ramping_lift = nil
; filament_travel_slope = nil
; filament_type = PETG
; filament_unload_time = 0
; filament_unloading_speed = 90
; filament_unloading_speed_start = 100
; filament_vendor = Generic
; filament_wipe = nil
; fill_angle = 45
; fill_density = 15%
; fill_pattern = grid
; first_layer_acceleration = 800
; first_layer_acceleration_over_raft = 0
; first_layer_bed_temperature = 85
; first_layer_extrusion_width = 0.42
; first_layer_height = 0.2
; first_layer_infill_speed = 0
; first_layer_speed = 20
; first_layer_speed_over_raft = 30
; first_layer_temperature = 240
; full_fan_speed_layer = 5
; fuzzy_skin = none
; fuzzy_skin_point_dist = 0.8
; fuzzy_skin_thickness = 0.3
; gap_fill_enabled = 1
; gap_fill_speed = 40
; gcode_comments = 0
; gcode_flavor = marlin
; gcode_label_objects = octoprint
; gcode_resolution = 0.0125
; gcode_substitutions =
; high_current_on_filament_swap = 0
; host_type = prusalink
; idle_temperature = nil
; infill_acceleration = 1000
; infill_anchor = 2.5
; infill_anchor_max = 12
; infill_every_layers = 1
; infill_extruder = 1
; infill_extrusion_width = 0.5
; infill_first = 0
; infill_overlap = 10%
; infill_speed = 85
; interface_shells = 0
; interlocking_beam = 0
; interlocking_beam_layer_count = 2
; interlocking_beam_width = 0.8
; interlocking_boundary_avoidance = 2
; interlocking_depth = 2
; interlocking_orientation = 22.5
; ironing = 0
; ironing_flowrate = 15%
; ironing_spacing = 0.1
; ironing_speed = 15
; ironing_type = top
; layer_gcode = ;AFTER_LAYER_CHANGE\n;[layer_z]
; layer_height = 0.3
; machine_limits_usage = emit_to_gcode
; machine_max_acceleration_e = 5000,5000
; machine_max_acceleration_extruding = 1250,1250
; machine_max_acceleration_retracting = 1250,1250
; machine_max_acceleration_travel = 1500,1250
; machine_max_acceleration_x = 1000,960
; machine_max_acceleration_y = 1000,960
; machine_max_acceleration_z = 200,200
; machine_max_feedrate_e = 120,120
; machine_max_feedrate_x = 200,100
; machine_max_feedrate_y = 200,100
; machine_max_feedrate_z = 12,12
; machine_max_jerk_e = 4.5,4.5
; machine_max_jerk_x = 8,8
; machine_max_jerk_y = 8,8
; machine_max_jerk_z = 0.4,0.4
; machine_min_extruding_rate = 0,0
; machine_min_travel_rate = 0,0
; max_fan_speed = 50
; max_layer_height = 0.25
; max_print_height = 210
; max_print_speed = 200
; max_volumetric_extrusion_rate_slope_negative = 0
; max_volumetric_extrusion_rate_slope_positive = 0
; max_volumetric_speed = 0
; min_bead_width = 85%
; min_fan_speed = 30
; min_feature_size = 25%
; min_layer_height = 0.07
; min_print_speed = 15
; min_skirt_length = 4
; mmu_segmented_region_interlocking_depth = 0
; mmu_segmented_region_max_width = 0
; multimaterial_purging = 140
; notes =
; nozzle_diameter = 0.4
; nozzle_high_flow = 0
; only_one_perimeter_first_layer = 0
; only_retract_when_crossing_perimeters = 0
; ooze_prevention = 0
; output_filename_format = {input_filename_base}_{layer_height}mm_{printing_filament_types}_{printer_model}_{print_time}.gcode
; over_bridge_speed = 0
; overhang_fan_speed_0 = 0
; overhang_fan_speed_1 = 0
; overhang_fan_speed_2 = 0
; overhang_fan_speed_3 = 0
; overhang_speed_0 = 15
; overhang_speed_1 = 15
; overhang_speed_2 = 20
; overhang_speed_3 = 25
; overhangs = 1
; parking_pos_retraction = 92
; pause_print_gcode = M601
; perimeter_acceleration = 800
; perimeter_extruder = 1
; perimeter_extrusion_width = 0.5
; perimeter_generator = arachne
; perimeter_speed = 50
; perimeters = 2
; physical_printer_settings_id =
; post_process =
; prefer_clockwise_movements = 0
; print_settings_id = 0.30mm DRAFT @MK3
; printer_model = MK3S
; printer_notes = Don't remove the following keywords! These keywords are used in the "compatible printer" condition of the print and filament profiles to link the particular print and filament profiles to this printer profile.\nPRINTER_VENDOR_PRUSA3D\nPRINTER_MODEL_MK3\n
; printer_settings_id = Original Prusa i3 MK3S & MK3S+
; printer_technology = FFF
; printer_variant = 0.4
; printer_vendor =
; profile_vendor = Prusa Research
; profile_version = 2.2.20
; raft_contact_distance = 0.2
; raft_expansion = 1.5
; raft_first_layer_density = 90%
; raft_first_layer_expansion = 3
; raft_layers = 0
; remaining_times = 1
; resolution = 0
; retract_before_travel = 1
; retract_before_wipe = 0%
; retract_layer_change = 1
; retract_length = 0.8
; retract_length_toolchange = 4
; retract_lift = 0.4
; retract_lift_above = 0
; retract_lift_below = 209
; retract_restart_extra = 0
; retract_restart_extra_toolchange = 0
; retract_speed = 35
; scarf_seam_entire_loop = 0
; scarf_seam_length = 20
; scarf_seam_max_segment_length = 1
; scarf_seam_on_inner_perimeters = 0
; scarf_seam_only_on_smooth = 1
; scarf_seam_placement = nowhere
; scarf_seam_start_height = 0%
; seam_gap_distance = 15%
; seam_position = aligned
; silent_mode = 1
; single_extruder_multi_material = 0
; single_extruder_multi_material_priming = 0
; skirt_distance = 2
; skirt_height = 3
; skirts = 0
; slice_closing_radius = 0.049
; slicing_mode = regular
; slowdown_below_layer_time = 15
; small_perimeter_speed = 30
; solid_infill_acceleration = 0
; solid_infill_below_area = 0
; solid_infill_every_layers = 0
; solid_infill_extruder = 1
; solid_infill_extrusion_width = 0.5
; solid_infill_speed = 80
; spiral_vase = 0
; staggered_inner_seams = 0
; standby_temperature_delta = -5
; start_filament_gcode = "{if printer_notes!~/.*(MK3.5|MINIIS).*/}\nM900 K{if printer_notes=~/.*PRINTER_MODEL_MINI.*/ and nozzle_diameter[0]==0.6}0.12{elsif printer_notes=~/.*PRINTER_MODEL_MINI.*/ and nozzle_diameter[0]==0.8}0.06{elsif printer_notes=~/.*PRINTER_MODEL_MINI.*/}0.2{elsif nozzle_diameter[0]==0.8}0.02{elsif nozzle_diameter[0]==0.6}0.04{else}0.08{endif} ; Filament gcode LA 1.5\n{if printer_notes=~/.*PRINTER_MODEL_MINI.*/};{elsif printer_notes=~/.*PRINTER_HAS_BOWDEN.*/}M900 K200{elsif nozzle_diameter[0]==0.6}M900 K24{elsif nozzle_diameter[0]==0.8};{else}M900 K45{endif} ; Filament gcode LA 1.0\n{endif}\n\n{if printer_notes=~/.*MINIIS.*/}\nM572 S{if nozzle_diameter[0]==0.6}0.22{elsif nozzle_diameter[0]==0.8}0.15{elsif nozzle_diameter[0]==0.4}0.36{elsif nozzle_diameter[0]==0.25}1.02{else}0{endif}\n{endif}\n\n{if printer_notes=~/.*MK3.5.*/}\nM572 S{if nozzle_diameter[0]==0.4}0.052{elsif nozzle_diameter[0]==0.5}0.042{elsif nozzle_diameter[0]==0.6}0.025{elsif nozzle_diameter[0]==0.8}0.018{elsif nozzle_diameter[0]==0.25}0.18{elsif nozzle_diameter[0]==0.3}0.1{else}0{endif} ; Filament gcode\n{endif}"
; start_gcode = M862.3 P "[printer_model]" ; printer model check\nM862.1 P[nozzle_diameter] ; nozzle diameter check\nM115 U3.14.1 ; tell printer latest fw version\nG90 ; use absolute coordinates\nM83 ; extruder relative mode\nM104 S[first_layer_temperature] ; set extruder temp\nM140 S[first_layer_bed_temperature] ; set bed temp\nM190 S[first_layer_bed_temperature] ; wait for bed temp\nM109 S[first_layer_temperature] ; wait for extruder temp\nG28 W ; home all without mesh bed level\nG80 X{first_layer_print_min[0]} Y{first_layer_print_min[1]} W{(first_layer_print_max[0]) - (first_layer_print_min[0])} H{(first_layer_print_max[1]) - (first_layer_print_min[1])} ; mesh bed levelling\n{if filament_settings_id[initial_tool]=~/.*Prusament PA11.*/}\nG1 Z0.3 F720\nG1 Y-3 F1000 ; go outside print area\nG92 E0\nG1 X60 E9 F1000 ; intro line\nG1 X100 E9 F1000 ; intro line\n{else}\nG1 Z0.2 F720\nG1 Y-3 F1000 ; go outside print area\nG92 E0\nG1 X60 E9 F1000 ; intro line\nG1 X100 E12.5 F1000 ; intro line\n{endif}\nG92 E0\nM221 S{if layer_height<0.075}100{else}95{endif}\n\n; Don't change E values below. Excessive value can damage the printer.\n{if print_settings_id=~/.*(DETAIL @MK3|QUALITY @MK3).*/}M907 E430 ; set extruder motor current{endif}\n{if print_settings_id=~/.*(SPEED @MK3|DRAFT @MK3).*/}M907 E538 ; set extruder motor current{endif}
; support_material = 0
; support_material_angle = 0
; support_material_auto = 1
; support_material_bottom_contact_distance = 0
; support_material_bottom_interface_layers = 0
; support_material_buildplate_only = 0
; support_material_closing_radius = 2
; support_material_contact_distance = 0.2
; support_material_enforce_layers = 0
; support_material_extruder = 0
; support_material_extrusion_width = 0.38
; support_material_interface_contact_loops = 0
; support_material_interface_extruder = 0
; support_material_interface_layers = 2
; support_material_interface_pattern = rectilinear
; support_material_interface_spacing = 0.2
; support_material_interface_speed = 80%
; support_material_pattern = rectilinear
; support_material_spacing = 2
; support_material_speed = 45
; support_material_style = grid
; support_material_synchronize_layers = 0
; support_material_threshold = 50
; support_material_with_sheath = 0
; support_material_xy_spacing = 60%
; support_tree_angle = 40
; support_tree_angle_slow = 30
; support_tree_branch_diameter = 2
; support_tree_branch_diameter_angle = 3
; support_tree_branch_diameter_double_wall = 3
; support_tree_branch_distance = 1
; support_tree_tip_diameter = 0.8
; support_tree_top_rate = 30%
; temperature = 240
; template_custom_gcode =
; thick_bridges = 0
; thin_walls = 0
; thumbnails = 160x120
; thumbnails_format = PNG
; toolchange_gcode =
; top_fill_pattern = monotoniclines
; top_infill_extrusion_width = 0.45
; top_one_perimeter_type = none
; top_solid_infill_acceleration = 0
; top_solid_infill_speed = 40
; top_solid_layers = 4
; top_solid_min_thickness = 0.7
; travel_acceleration = 0
; travel_lift_before_obstacle = 0
; travel_max_lift = 0
; travel_ramping_lift = 0
; travel_slope = 0
; travel_speed = 180
; travel_speed_z = 12
; use_firmware_retraction = 0
; use_relative_e_distances = 1
; use_volumetric_e = 0
; variable_layer_height = 1
; wall_distribution_count = 1
; wall_transition_angle = 10
; wall_transition_filter_deviation = 25%
; wall_transition_length = 100%
; wipe = 1
; wipe_into_infill = 0
; wipe_into_objects = 0
; wipe_tower = 1
; wipe_tower_acceleration = 0
; wipe_tower_bridging = 10
; wipe_tower_brim_width = 2
; wipe_tower_cone_angle = 0
; wipe_tower_extra_flow = 100%
; wipe_tower_extra_spacing = 100%
; wipe_tower_extruder = 0
; wipe_tower_no_sparse_layers = 0
; wipe_tower_width = 60
; wiping_volumes_matrix = 0
; wiping_volumes_use_custom_matrix = 0
; xy_size_compensation = 0
; z_offset = 0
; prusaslicer_config = end
M84 ; disable motors
